FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
}

ENABLE_PROXY_FIX = True
SECRET_KEY = "YOUR_OWN_RANDOM_GENERATED_STRING"
SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:postgres@db/superset'
SUPERSET_LOAD_EXAMPLES = True