-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.author
(
    id integer NOT NULL,
    born_dce integer NOT NULL,
    born_h integer NOT NULL,
    place_of_death text COLLATE pg_catalog."default",
    name_short_ar text COLLATE pg_catalog."default" NOT NULL,
    name_short_dmg text COLLATE pg_catalog."default" NOT NULL,
    name_short_simple text COLLATE pg_catalog."default" NOT NULL,
    name_ar text COLLATE pg_catalog."default" NOT NULL,
    name_dmg text COLLATE pg_catalog."default" NOT NULL,
    name_simple text COLLATE pg_catalog."default" NOT NULL,
    name_alt_ar text COLLATE pg_catalog."default",
    name_alt_dmg text COLLATE pg_catalog."default",
    name_alt_simple text COLLATE pg_catalog."default",
    name_alt_2_ar text COLLATE pg_catalog."default",
    name_alt_2_dmg text COLLATE pg_catalog."default",
    name_alt_2_simple text COLLATE pg_catalog."default",
    name_alt_2_translated text COLLATE pg_catalog."default",
    CONSTRAINT author_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tafsir
(
    id integer NOT NULL,
    title_short_ar text COLLATE pg_catalog."default" NOT NULL,
    title_short_dmg text COLLATE pg_catalog."default" NOT NULL,
    title_short_simple text COLLATE pg_catalog."default" NOT NULL,
    title_ar text COLLATE pg_catalog."default" NOT NULL,
    title_dmg text COLLATE pg_catalog."default" NOT NULL,
    title_simple text COLLATE pg_catalog."default" NOT NULL,
    title_alt_ar text COLLATE pg_catalog."default",
    title_alt_dmg text COLLATE pg_catalog."default",
    title_alt_simple text COLLATE pg_catalog."default",
    madhhab_id integer NOT NULL,
    CONSTRAINT commentary_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.doctrine
(
    id integer NOT NULL,
    label text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT doctrine_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.exegetical_interest
(
    id integer NOT NULL,
    label text COLLATE pg_catalog."default" NOT NULL,
    from_year integer,
    to_year integer,
    CONSTRAINT exegetical_interest_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.madhhab
(
    id integer NOT NULL,
    name_ar text COLLATE pg_catalog."default" NOT NULL,
    name_en text COLLATE pg_catalog."default" NOT NULL,
    name_short text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT madhhab_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.period
(
    id integer NOT NULL,
    label text COLLATE pg_catalog."default" NOT NULL,
    from_year integer NOT NULL,
    to_year integer NOT NULL,
    CONSTRAINT period_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.region
(
    id integer NOT NULL,
    label text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT region_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.school_of_thought
(
    id integer NOT NULL,
    label text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT school_of_thought_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.author_tafsir
(
    author_id integer NOT NULL,
    tafsir_id integer NOT NULL,
    cert text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.author_region
(
    author_id integer NOT NULL,
    region_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.region_period
(
    region_id integer NOT NULL,
    period_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.author_school_of_thought
(
    author_id integer NOT NULL,
    school_of_thought_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.author_doctrine
(
    author_id integer NOT NULL,
    doctrine_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.author_exegetical_interest
(
    author_id integer NOT NULL,
    exegetical_interest_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.author_period
(
    author_id integer NOT NULL,
    period_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.chapter
(
    id text NOT NULL,
    tafsir_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subchapter
(
    id text NOT NULL,
    chapter_id text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sentence
(
    id text NOT NULL,
    subchapter_id text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.quote
(
    id text NOT NULL,
    sentence_id text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.word
(
    id text NOT NULL,
    sentence_id text,
    quote_id text,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.tafsir
    ADD CONSTRAINT madhhab_id FOREIGN KEY (madhhab_id)
    REFERENCES public.madhhab (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.author_tafsir
    ADD FOREIGN KEY (author_id)
    REFERENCES public.author (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.author_tafsir
    ADD FOREIGN KEY (tafsir_id)
    REFERENCES public.tafsir (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.author_region
    ADD FOREIGN KEY (author_id)
    REFERENCES public.author (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.author_region
    ADD FOREIGN KEY (region_id)
    REFERENCES public.region (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.region_period
    ADD FOREIGN KEY (region_id)
    REFERENCES public.region (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.region_period
    ADD FOREIGN KEY (period_id)
    REFERENCES public.period (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.author_school_of_thought
    ADD FOREIGN KEY (author_id)
    REFERENCES public.author (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.author_school_of_thought
    ADD FOREIGN KEY (school_of_thought_id)
    REFERENCES public.school_of_thought (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.author_doctrine
    ADD FOREIGN KEY (author_id)
    REFERENCES public.author (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.author_doctrine
    ADD FOREIGN KEY (doctrine_id)
    REFERENCES public.doctrine (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.author_exegetical_interest
    ADD FOREIGN KEY (author_id)
    REFERENCES public.author (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.author_exegetical_interest
    ADD FOREIGN KEY (exegetical_interest_id)
    REFERENCES public.exegetical_interest (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.author_period
    ADD FOREIGN KEY (author_id)
    REFERENCES public.author (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.author_period
    ADD FOREIGN KEY (period_id)
    REFERENCES public.period (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.chapter
    ADD CONSTRAINT tafsir_id FOREIGN KEY (tafsir_id)
    REFERENCES public.tafsir (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.subchapter
    ADD FOREIGN KEY (chapter_id)
    REFERENCES public.chapter (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sentence
    ADD CONSTRAINT subchapter_id FOREIGN KEY (subchapter_id)
    REFERENCES public.subchapter (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.quote
    ADD CONSTRAINT sentence_id FOREIGN KEY (sentence_id)
    REFERENCES public.sentence (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.word
    ADD CONSTRAINT quote_id FOREIGN KEY (quote_id)
    REFERENCES public.quote (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.word
    ADD CONSTRAINT sentence_id FOREIGN KEY (sentence_id)
    REFERENCES public.sentence (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;